//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.TimeTable = new HashSet<TimeTable>();
            this.Student = new HashSet<Student>();
            this.Prerequisites = new HashSet<Prerequisites>();
        }
    
        public int CourseID { get; set; }
        public int CourseCode { get; set; }
        public string CourseName { get; set; }
        public string Term_associated { get; set; }
        public Nullable<int> CreditHours { get; set; }
    
        public virtual ICollection<TimeTable> TimeTable { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Prerequisites> Prerequisites { get; set; }
    }
}
