//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Course = new HashSet<Course>();
        }
    
        public int StudentID { get; set; }
        public string S_email { get; set; }
        public string S_name { get; set; }
        public string S_pw { get; set; }
        public string S_phone { get; set; }
        public Nullable<int> Credits_aquired { get; set; }
    
        public virtual ICollection<Course> Course { get; set; }
    }
}
