//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int TimeTableID { get; set; }
        public Nullable<int> Section_ID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Registered { get; set; }
        public string CourseTime { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
